language: node_js
node_js: 12
install:
- npm install
script:
- npm run lint
after_success:
- npx semantic-release
env:
  global:
  # GH_TOKEN
  - secure: kuLoGeg37ASpPr6XEfADXKKlL/jpmnXX5gqhjJycQ+liogUQN+9NVzqeaPfGPTz9sY34F/dG7F1bR8BxGl1AxpqQsSwSD1lhCNF4j5K3bT6KIr04B1X5TDyaEXU40IP0nyrT0tFk3aaFP+mw6YHgg0KXNj/wuWqwwGY03roT31+E6RTDhlwuE443u4l6+ApdjmQP9Dmm0H3i220PtqU0RcNSXizs+kdlACfquwHHMjyhRFLG71++bKuV9YWrio16yDwjooKsqsW7faPeGVwDRPJvwVCyBjsZuR7hLkMOWIm1CB4xeX94jy2o8q7zGzjDxUyLYI3cliMLpsfcsPFZLpoNnh4NkeVLY9beZ0IdAAtkjm59mddGAQp630zLJSSzmKDTVDKLRIN0Ns+wslvmuzVb8LBSYa/hKyg1/qjl77IJT9Mz0Sbm2r+Wj9bviyXt4CguM7Qizpst0mDlxxN9D74iYvx6VQoLbOH5uy5kCXRYnSjZHlaOc2/GlNrXQ9eP/8PLam556R8IHvvzfFodeSAgxCwTMypkWBFf55b74OjT+Twf3e0UcjdSJeND7f8Rnk1pUOsnUUY0LeZS/CngPUhPVJmDUkHyoQupq1OMALjvGJBwKaQihp3DfqfUeFzRm3ajkpJKzx2VDxi6zWg08bidClD7JWd+x1mGYw3roQk=
  # NPM_TOKEN
  - secure: XkgAdCg2ZHbvxds1u7UPCvcRbRZRwn2wiokz+pkyoZd0IKLEhbImY4DaOgolJ/9NfeCqEqbDIexGy74JRJptgKe6MPmlZiDPj6azhkgI0HD+QLvvkntj3E+m0ssSlnbwb+dicea6Fxkk9JKNln8XcU0XEDo922Q55Mz4t07aYu7i3qhfSP/1oBYGsxd/IFmuR8fhvWT8hEEO0Lx0qAloXql5ECK01DeuUGsVUkY77mpyNwRUDWALWHe/y/stYcUwyu4pxjUQvyn3Rz4FrsrcbpIS3/4T5X4ImMyMwcRaFymRJwkBypjHeJPWsH5HZ5XLwED6o7YGAuVIoRDLOuJg3O6vxwNGqv7qDvm+r1C3Gj7GzfIIyXb+9lDWCifrWzY7v14Am/v0MZ7vbdrcjMXTXGVZ+2TVva9T1m6pz/mR+dNqVY765fn/iibLSuDKdAyR0QXoQoBp7awxbPpjN+gQSwwJpaCtgJHfOHl4+Jc47jt0OS0UQY/ilm+4Xvf2MUS4kZkp/y5iwBIoFjr1MBkkXDkD9WCENrwrNeFmbK7ijdI0nlE7ZvYdSaI9ohstNFKqhaZ0r16v7t3z8xP+nL0yqM+HWLyAp2f1WsTuTMpwAY4+b47ftD2msCWWpY09BcfxmAwl8KKHIVgwSA7p6xMYk/V7P4vzKlI+IpmEWC4Xgyc=
